services:
  room-service-db:
    extends:
      service: room-service-db
      file: ./RoomService/docker-compose.yml

  user-service-db:
    extends:
      service: user-service-db
      file: ./UserService/docker-compose.yml

  room-service:
    extends:
      service: room-service
      file: ./RoomService/docker-compose.yml

networks:
  hotel_network:
    driver: bridge