version: "3.9"

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: hotel_r
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 654321
      POSTGRES_PORT: 5433
    volumes:
      - database_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - hotel_network

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: application
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      - DATABASE_IP=host.docker.internal
    depends_on:
      - database
    networks:
      - hotel_network
networks:
  hotel_network:
    driver: bridge
volumes:
  database_data:
    driver: local