##### port #####
server:
  port: 8086

##### data postgresql #####
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db   # PostgreSQL veritabanı URL'si
    username: postgres                                    # Veritabanı kullanıcı adı
    password: 4321                                 # Veritabanı şifresi
    driver-class-name: org.postgresql.Driver             # PostgreSQL JDBC sürücüsü
  jpa:
    hibernate:
      ddl-auto: update                                 # Veritabanı şemasının otomatik güncellenmesi
    show-sql: true

##### swagger-ui path #####
springdoc:
  swagger-ui:
    path: /swagger-ui.html
