server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db?currentSchema=room_hotel_db
    username: postgres
    password: 4321
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

