server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db?currentSchema=room_hotel_db
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:4321}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

