##### port #####
server:
  port: 8082

# RoomService
##### data postgresql #####
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hotel_db?currentSchema=hotelroom
    username: postgres
    password: 4321
    driver-class-name: org.postgresql.Driver

